# Generated by Django 5.2.8 on 2026-03-13 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('tipo_movimiento', models.CharField(choices=[('venta', 'Venta'), ('ajuste', 'Ajuste Manual'), ('cancelacion', 'Cancelación de Venta'), ('entrada', 'Entrada de Stock')], max_length=20)),
                ('referencia', models.CharField(blank=True, help_text='ID de venta o ajuste relacionado', max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='productos.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['producto'], name='inventario__product_94c37b_idx'), models.Index(fields=['-created_at'], name='inventario__created_994206_idx')],
            },
        ),
    ]
