# Generated by Django 5.2.8 on 2026-03-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('venta', 'Venta'), ('ajuste', 'Ajuste Manual'), ('cancelacion', 'Cancelación de Venta'), ('entrada', 'Entrada de Stock'), ('devolucion', 'Devolución')], max_length=20),
        ),
    ]
