# Generated by Django 5.2.8 on 2026-03-14 03:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('defectuoso', 'Producto Defectuoso'), ('cambio_idea', 'Cambio de Idea'), ('producto_incorrecto', 'Producto Incorrecto'), ('dañado', 'Producto Dañado'), ('no_solicitado', 'No Solicitado'), ('otro', 'Otro')], max_length=20)),
                ('tipo_reembolso', models.CharField(choices=[('efectivo', 'Reembolso en Efectivo'), ('transferencia', 'Devolución a Transferencia'), ('credito', 'Crédito para Próximas Compras')], max_length=20)),
                ('total_devuelto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_procesadas', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='ventas.venta')),
            ],
            options={
                'ordering': ['-fecha_devolucion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detalle_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.detalleventa')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.devolucion')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Devolución',
            },
        ),
        migrations.AddIndex(
            model_name='devolucion',
            index=models.Index(fields=['-fecha_devolucion'], name='ventas_devo_fecha_d_c21509_idx'),
        ),
        migrations.AddIndex(
            model_name='devolucion',
            index=models.Index(fields=['venta'], name='ventas_devo_venta_i_572fe2_idx'),
        ),
    ]
