# Generated by Django 5.2.8 on 2026-04-13 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_devolucion_detalledevolucion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='estado',
            field=models.CharField(choices=[('pendiente_aprobacion', 'Pendiente de Aprobación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente_aprobacion', max_length=20),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='razon_rechazo',
            field=models.TextField(blank=True, help_text='Razón del rechazo (si aplica)', null=True),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='usuario_aprobacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='devolucion',
            index=models.Index(fields=['estado'], name='ventas_devo_estado_3f255e_idx'),
        ),
    ]
