# Generated by Django 5.2.8 on 2026-03-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionReportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato_moneda', models.CharField(default='MXN', max_length=5)),
                ('mostrar_detalles_texto', models.BooleanField(default=True)),
                ('margen_ganancias', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de margen para análisis', max_digits=5, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Reportes',
                'verbose_name_plural': 'Configuración de Reportes',
            },
        ),
    ]
