# Generated by Django 5.2.8 on 2026-03-22 19:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_minima', models.PositiveIntegerField(help_text='Cantidad mínima para aplicar este precio (ej: 100)')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio por unidad cuando se alcanzan las cantidades mínimas', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('descripcion', models.CharField(blank=True, help_text="Ej: 'Precio mayoreo', 'Descuento volumen grande'", max_length=100, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas_precios', to='productos.producto')),
            ],
            options={
                'verbose_name_plural': 'Escalas de Precios',
                'ordering': ['producto', 'cantidad_minima'],
                'indexes': [models.Index(fields=['producto', 'cantidad_minima'], name='productos_e_product_93d0c8_idx')],
                'unique_together': {('producto', 'cantidad_minima')},
            },
        ),
    ]
