# Generated by Django 5.2.8 on 2026-03-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_escalaprecios'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_flexible',
            field=models.BooleanField(default=False, help_text='Si está marcado, permite al vendedor ingresar un precio personalizado en la venta'),
        ),
        migrations.DeleteModel(
            name='EscalaPrecios',
        ),
    ]
