# Generated by Django 5.2.8 on 2026-03-22 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_precio_flexible_delete_escalaprecios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_flexible',
        ),
    ]
