# Generated by Django 5.2.8 on 2026-03-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_producto_precio_flexible'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_servicio',
            field=models.BooleanField(default=False, help_text='Marcar si es un servicio (sin control de stock)'),
        ),
    ]
