# Generated by Django 5.2.8 on 2026-03-23 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_es_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='es_servicio',
        ),
    ]
