# Generated by Django 5.2.8 on 2026-03-13 14:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorteCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_corte', models.DateField(auto_now_add=True)),
                ('total_ventas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_transferencias', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Corte de caja',
                'verbose_name_plural': 'Cortes de caja',
                'ordering': ['-fecha_corte'],
                'unique_together': {('fecha_corte',)},
            },
        ),
    ]
