# Generated by Django 5.2.8 on 2026-03-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cortecaja',
            options={'ordering': ['-fecha_corte', '-turno'], 'verbose_name': 'Corte de caja', 'verbose_name_plural': 'Cortes de caja'},
        ),
        migrations.AlterUniqueTogether(
            name='cortecaja',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='turno',
            field=models.IntegerField(choices=[(1, 'Turno 1 (Mediodía - 1 PM)'), (2, 'Turno 2 (Noche - 9 PM)')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='cortecaja',
            unique_together={('fecha_corte', 'turno')},
        ),
    ]
