# Generated by Django 5.2.8 on 2026-04-13 01:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_alter_cortecaja_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortecaja',
            name='diferencia_efectivo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='estado_cuadratura',
            field=models.CharField(choices=[('cuadrado', 'Cuadrado'), ('diferencia', 'Con Diferencia'), ('pendiente', 'Pendiente Validación')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='monto_efectivo_ingresado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='monto_transferencias_ingresado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='notas_discrepancia',
            field=models.TextField(blank=True, help_text='Explicar discrepancias encontradas', null=True),
        ),
    ]
